#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["App.Backend.API/App.Backend.API.csproj", "App.Backend.API/"]
RUN dotnet restore "App.Backend.API/App.Backend.API.csproj"
COPY . .
WORKDIR "/src/App.Backend.API"
RUN dotnet build "App.Backend.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "App.Backend.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "App.Backend.API.dll"]